from tkinter import *
window = Tk()
window.title("Assignment 1")
lbl1 = Label(window, text="Name: ")
lbl1.grid(column=1, row=1)
txt = Entry(window,width=30)
txt.grid(column=2, row=1)
lbl2 = Label(window, text="Gender: ")
lbl2.grid(column=1, row=2)
rad1 = Radiobutton(window,text='Male', value=1)
rad2 = Radiobutton(window,text='Female', value=2)
rad1.grid(column=2, row=2)
rad2.grid(column=3, row=2)
lbl3 = Label(window, text="Hobbies: ")
lbl3.grid(column=1, row=3)
chk_state = BooleanVar()
chk_state.set(False)
chk1 = Checkbutton(window, text='Music', var=chk_state)
chk1.grid(column=2, row=3)
chk2 = Checkbutton(window, text='Cricket', var=chk_state)
chk2.grid(column=3, row=3)
chk3 = Checkbutton(window, text='Coding', var=chk_state)
chk3.grid(column=4, row=3)
chk4 = Checkbutton(window, text='Football', var=chk_state)
chk4.grid(column=5, row=3)
lbl4 = Label(window, text="Courses: ")
lbl4.grid(column=1, row=4)
listbox = Listbox(window)
listbox.insert(1,"Java")
listbox.insert(2, "C++")
listbox.insert(3, "Python")
listbox.insert(4, "PHP")
listbox.grid(column=2, row=4)
window.mainloop()
